/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    void userCanLoginByUsername() {

        WebDriverManager.chromedriver().setup();

     //Chromeを起動する
     WebDriver driver = new ChromeDriver();
     //指定したURLに遷移する
     driver.get("https://www.google.co.jp");
     
    }
    
}
